models/__init__.py
models/base_model.py
models/engine/file_storage.py
test_base_model_dict.py
test_save_reload_base_model.py
tests/test_models/test_base_model.py

Adding tasks 4 and 5
AttributeError: 'BaseModel' object has no attribute 'id'

Adding tasks 4 and 5

---

.gitignore
console.py
models/engine/file_storage.py
tests/test_models/test_base_model.py
tests/test_models/test_engine/test_file_storage.py

Adding console.py, unittest and .gitignore

Adding console.py, unittest and .gitignore

---

AUTHORS
console.py
generate-authors.sh

classes dictionary inside HBNBCommand and methods do_create and do_show implemented

methods do_create and do_show implemented

---

console.py
models/__init__.py
models/base_model.py
models/engine/file_storage.py

Adding changes to all methods in the console and the methods reload and destroy in file_Storage

Adding changes to methods in the console and filestorage

---

console.py
models/__init__.py
models/amenity.py
models/city.py
models/engine/file_storage.py
models/place.py
models/review.py
models/state.py
models/user.py
test_save_reload_place.py
test_save_reload_user.py

destroy doesn't work good yet, the changes after that are no made

tasks 7, 8, 9, 10 v0

---

console.py
models/engine/file_storage.py

to_destroy method fixed and method delete added

to_destroy method fixed

---

models/engine/file_storage.py
tests/test_models/test_base_model.py
tests/test_models/test_engine/test_file_storage.py

tests done for file_storage and base_model, file_storage fixed with pep8

tests for file_storage and base_model

---

console.py
models/base_model.py

- In the function destroy of the console some redundant lines with what is indicated in the attempts, except
- Some conditionals are checked in the __init__ of the BaseModel class

Fixing logical failures in base_model.py and console.py

---

models/base_model.py

Changing the handling of args and kwargs in the init

Fixing BaseModel __init__

---

models/base_model.py

Adding conditional for storage new objects in BaseModel

Adding conditional for storage new objects in BaseModel

---

models/base_model.py

Leaving the best version of basemodel: The last attempts affected the checks

Leaving the best version of basemodel

---

README.md
models/base_model.py

base_model new version

---

models/base_model.py

base_model conditions fixed with test from holberton

base_model conditions fixed with test

---

models/base_model.py
models/engine/file_storage.py

reload and save methods changed

reload and save methods changed

---

models/engine/file_storage.py

all method only returning objects

all method only returning objects

---

console.py

Deleting print

---

tests/test_models/test_amenity.py

__init__ in folder test and amenity commented

__init__ in folder test and amenity commented

---

console.py
models/engine/file_storage.py

Fixing save method in file_storage

Fixing save method in file_storage

---

tests/test_models/test_base_model.py

tests for base_model changed

---

tests/test_models/test_engine/test_file_storage.py

tests for file_storage changed

tests for file_storage changed

---

tests/test_models/test_engine/test_file_storage.py

tests_file_storage as before

---

console.py

Adding function loop_dic for update with a dictionary

Adding changes in the console for task 16

---

tests/test_models/test_base_model.py

comments for tests_base_model improved

comments for tests_base_model improved

---

tests/test_console.py

mistake of pep8 fixed

---

tests/test_models/test_engine/test_file_storage.py

tests for new and reload methods in test_file_storage

tests for new and reload methods
